[package]
name = "ext_trait"
version = "0.1.0"
authors = ["T0mstone <realt0mstone@gmail.com>"]
keywords = ["proc_macro", "procmacro", "trait"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"

[dependencies.syn]
version = "1.0"
features = ["full"]

